In [11]:
import pandas as pd
import numpy as np

In [2]:
s_countries = pd.Series(['India', 'USA', 'UK', 'Germany', 'France'], name='GlobalCountry')
print(s_countries)

0      India
1        USA
2         UK
3    Germany
4     France
Name: GlobalCountry, dtype: object

In [10]:
movies = pd.read_csv('DataSet_used/bollywood.csv', index_col='movie').squeeze('columns')
movies.sample(5)

movie
Lagaan Rathore 4    Amitabh Bachchan
Jawan Zindagi 2        Ranveer Singh
Dilwale Rathore        Ranveer Singh
Gully Rathore            Salman Khan
Garam Dhamaka            Irrfan Khan
Name: lead, dtype: object

In [4]:
shape = movies.shape
print(shape)

(500,)

In [5]:
movies.head(6)

movie
Uri: The Surgical Strike     Vicky Kaushal
Battalion 609               Shoaib Ibrahim
Khatti Hungama                 Anil Kapoor
Chennai Singh 5               Arjun Kapoor
Krrish Rathore                  Aamir Khan
Krrish Zindagi 5             Kartik Aaryan
Name: lead, dtype: object

In [6]:
df_demo = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Score': [85.5, 90.0, 95.5, 80.0, 75.5]
}, index = ['A1', 'A2', 'A3', 'A4', 'A5'])
df_demo.head()

       Name  Age         City  Score
A1    Alice   25     New York   85.5
A2      Bob   30  Los Angeles   90.0
A3  Charlie   35      Chicago   95.5
A4    David   40      Houston   80.0
A5      Eva   45      Phoenix   75.5

In [7]:
df_demo.iloc[0, 1:4:2], df_demo.iloc[-1, 1:4:2]

(Age        25
 Score    85.5
 Name: A1, dtype: object,
 Age        45
 Score    75.5
 Name: A5, dtype: object)

In [8]:
df_demo.iloc[0:3, -2:]

           City  Score
A1     New York   85.5
A2  Los Angeles   90.0
A3      Chicago   95.5