In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DataSet_used\\test_dataset.csv")

In [3]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product_Name,Quantity,Discount,Sales,Payment_Mode,Rating,Delivery_Days,Returned
0,ORD-1001,11-03-2024,Arjun,Chandigarh,Beauty,Moisturizer,1.0,0.25,111.75,UPI,5,9,Yes
1,ORD-1002,01/24/2024,Ritika,Chandigarh,Stationery,Stapler,1.0,0,799,Net Banking,2.5,9,No
2,ORD-1003,24-04-2024,Kabir,Mohali,Beauty,Face Wash,7.0,0.05,33243.35,Card,5,7,No
3,ORD-1004,27-01-2024,NaN,Jaipur,Furniture,Chair,4.0,0.1,716.4,Cash,3.5,10,No
4,ORD-1005,21-01-2024,Tanya,Mohali,Electronics,Power Bank,2.0,0.15,1698.3,Cash,4.5,4,Yes

In [4]:
df.tail()

,Order_ID,Order_Date,Customer_Name,City,Category,Product_Name,Quantity,Discount,Sales,Payment_Mode,Rating,Delivery_Days,Returned
95,ORD-1041,17-04-2024,Sahil,Bengaluru,Grocery,Sugar,3.0,0.05,1137.15,Net Banking,3.5,7,Yes
96,ORD-1006,01/21/2024,Arjun,Mumbai,Electronics,Charger,4.0,0.1,17996.4,Cash,4,6,No
97,ORD-1056,30-01-2024,Kabir,Chandigarh,electronics,Shirt,8.0,0.25,1194,Cash,3.5,3,Yes
98,ORD-1061,08-01-2024,Rohit,Pune,Clothing,Jeans,7.0,0.1,6293.7,cod,3,6,No
99,ORD-1016,18-05-2024,Ritika,Mohali,Stationery,File Folder,10.0,0.05,16618.35,Cash,4,9,No

In [5]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 100
Number of columns: 13

In [6]:
df.columns.to_list()

['Order_ID',
 'Order_Date',
 'Customer_Name',
 'City',
 'Category',
 'Product_Name',
 'Quantity',
 'Discount',
 'Sales',
 'Payment_Mode',
 'Rating',
 'Delivery_Days',
 'Returned']

In [7]:
df.dtypes

Order_ID             str
Order_Date           str
Customer_Name        str
City                 str
Category             str
Product_Name         str
Quantity         float64
Discount             str
Sales                str
Payment_Mode         str
Rating               str
Delivery_Days        str
Returned             str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       100 non-null    str
 1   Order_Date     100 non-null    str
 2   Customer_Name  99 non-null     str
 3   City           99 non-null     str
 4   Category       99 non-null     str
 5   Product_Name   100 non-null    str
 6   Quantity       99 non-null     float64
 7   Discount       99 non-null     str
 8   Sales          99 non-null     str
 9   Payment_Mode   100 non-null    str
 10  Rating         99 non-null     str
 11  Delivery_Days  99 non-null     str
 12  Returned       100 non-null    str
dtypes: float64(1), str(12)
memory usage: 16.7 KB

In [9]:
df.describe()

         Quantity
count   99.000000
mean     5.555556
std     11.919134
min     -3.000000
25%      2.000000
50%      4.000000
75%      7.000000
max    120.000000

In [10]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    1
City             1
Category         1
Product_Name     0
Quantity         1
Discount         1
Sales            1
Payment_Mode     0
Rating           1
Delivery_Days    1
Returned         0
dtype: int64

In [11]:
print(f"% of missing values:", df.isnull().mean() * 100)

% of missing values: Order_ID         0.0
Order_Date       0.0
Customer_Name    1.0
City             1.0
Category         1.0
Product_Name     0.0
Quantity         1.0
Discount         1.0
Sales            1.0
Payment_Mode     0.0
Rating           1.0
Delivery_Days    1.0
Returned         0.0
dtype: float64

*Task 4*

In [12]:
df["Sales"] = pd.to_numeric(df["Sales"], errors="coerce")
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce")
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")
df["Delivery_Days"] = pd.to_numeric(df["Delivery_Days"], errors="coerce")
df.dtypes

Order_ID             str
Order_Date           str
Customer_Name        str
City                 str
Category             str
Product_Name         str
Quantity         float64
Discount         float64
Sales            float64
Payment_Mode         str
Rating           float64
Delivery_Days    float64
Returned             str
dtype: object

In [13]:
df_clean = df.copy()

In [14]:
df_clean.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    1
City             1
Category         1
Product_Name     0
Quantity         1
Discount         3
Sales            2
Payment_Mode     0
Rating           2
Delivery_Days    2
Returned         0
dtype: int64

In [15]:
df_clean.dtypes

Order_ID             str
Order_Date           str
Customer_Name        str
City                 str
Category             str
Product_Name         str
Quantity         float64
Discount         float64
Sales            float64
Payment_Mode         str
Rating           float64
Delivery_Days    float64
Returned             str
dtype: object

In [16]:
df_clean["Customer_Name"] = df_clean["Customer_Name"].fillna("Unknown")
df_clean["Customer_Name"].isnull().sum()

np.int64(0)

In [17]:
df_clean['Category'] = df_clean['Category'].fillna(df_clean['Category'].mode()[0])
df_clean["Category"].isnull().sum()

np.int64(0)

In [18]:
df_clean['City'] = df_clean['City'].fillna(df_clean['City'].mode()[0])
df_clean["City"].isnull().sum()

np.int64(0)

In [19]:
df_clean.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
City             0
Category         0
Product_Name     0
Quantity         1
Discount         3
Sales            2
Payment_Mode     0
Rating           2
Delivery_Days    2
Returned         0
dtype: int64

In [20]:
median_days = round(df_clean['Delivery_Days'].median(),1)
df_clean['Delivery_Days'] = df_clean['Delivery_Days'].fillna(median_days)

In [21]:
median_val = df_clean['Rating'].median()
df_clean['Rating'] = df_clean['Rating'].fillna(median_val)

In [22]:
# df_clean = df_clean.dropna(subset="Sales")
median_sale = df_clean['Sales'].median()
print(median_sale)
df_clean['Sales'] = df_clean['Sales'].fillna(median_sale)

1597.2

In [23]:
df_clean["Discount"] = df_clean["Discount"].fillna(df_clean["Discount"].median())

In [24]:
df_clean['Quantity'] = df_clean['Quantity'].fillna(df_clean["Quantity"].median())

In [25]:
print(df_clean.isnull().sum())

Order_ID         0
Order_Date       0
Customer_Name    0
City             0
Category         0
Product_Name     0
Quantity         0
Discount         0
Sales            0
Payment_Mode     0
Rating           0
Delivery_Days    0
Returned         0
dtype: int64

In [26]:
df_clean = df_clean.drop_duplicates()
print("Duplicate values before:", len(df[df.duplicated()]))
print("Duplicate values after treatment:", len(df_clean[df_clean.duplicated()]))

Duplicate values before: 8
Duplicate values after treatment: 0

In [27]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 92 entries, 0 to 94
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       92 non-null     str
 1   Order_Date     92 non-null     str
 2   Customer_Name  92 non-null     str
 3   City           92 non-null     str
 4   Category       92 non-null     str
 5   Product_Name   92 non-null     str
 6   Quantity       92 non-null     float64
 7   Discount       92 non-null     float64
 8   Sales          92 non-null     float64
 9   Payment_Mode   92 non-null     str
 10  Rating         92 non-null     float64
 11  Delivery_Days  92 non-null     float64
 12  Returned       92 non-null     str
dtypes: float64(5), str(8)
memory usage: 14.9 KB

In [28]:
df_clean['Category'] = df_clean['Category'].str.strip().str.title()
df_clean['Customer_Name'] = df_clean['Customer_Name'].str.strip().str.title()
df_clean['City'] = df_clean['City'].str.strip().str.title()
df_clean['Product_Name'] = df_clean['Product_Name'].str.strip().str.title()
df_clean['Payment_Mode'] = df_clean['Payment_Mode'].str.strip().str.title()
df_clean['Returned'] = df_clean['Returned'].str.strip().str.title()

In [29]:
for cols in ['Category', 'City', 'Payment_Mode', 'Product_Name', 'Customer_Name', 'Returned']:
    print(f"Unique values in '{cols}': {df_clean[cols].unique().tolist()}\n\n")

Unique values in 'Category': ['Beauty', 'Stationery', 'Furniture', 'Electronics', 'Clothing', 'Grocery', 'Clothng']


Unique values in 'City': ['Chandigarh', 'Mohali', 'Jaipur', 'Mumbai', 'Bengaluru', 'Delhi', 'Pune', 'Lucknow']


Unique values in 'Payment_Mode': ['Upi', 'Net Banking', 'Card', 'Cash', 'Cod']


Unique values in 'Product_Name': ['Moisturizer', 'Stapler', 'Face Wash', 'Chair', 'Power Bank', 'Charger', 'Desk', 'Shirt', 'Lip Balm', 'Marker', 'Tea Pack', 'Jeans', 'File Folder', 'Kurti', 'Cooking Oil', 'Notebook', 'Bookshelf', 'Wheat Flour', 'Pen Set', 'Keyboard', 'Sugar', 'Stool', 'T-Shirt', 'Headphones', 'Sunscreen', 'Jacket', 'Serum']


Unique values in 'Customer_Name': ['Arjun', 'Ritika', 'Kabir', 'Unknown', 'Tanya', 'Rahul', 'Neha', 'Rohit', 'Mehak', 'Priya', 'Sneha', 'Aman', 'Simran', 'Nikhil', 'Sahil', 'Isha', 'Karan', 'Manpreet', 'Anjali', 'Jaspreet', 'Varun']


Unique values in 'Returned': ['Yes', 'No']

In [30]:
df_clean['Order_Date'].head(30)

0     11-03-2024
1     01/24/2024
2     24-04-2024
3     27-01-2024
4     21-01-2024
5     01/21/2024
6     09-03-2024
7     24-03-2024
8     16-06-2024
9     05/29/2024
10    09-06-2024
11    30-01-2024
12    15-02-2024
13    03/23/2024
14    04-05-2024
15    18-05-2024
16    27-03-2024
17    01/19/2024
18    01-05-2024
19    14-01-2024
20    18-04-2024
21    03-01-2024
22    08-03-2024
23    28-05-2024
24    10-05-2024
25    06-01-2024
26    08-03-2024
27    17-05-2024
28    29-06-2024
29    05/21/2024
Name: Order_Date, dtype: str

In [31]:
df_clean['Order_Date'] = pd.to_datetime(df_clean['Order_Date'], format = "mixed", errors="coerce")

print("Invalid dates:", df_clean["Order_Date"].isnull().sum())

Invalid dates: 1

In [32]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 92 entries, 0 to 94
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       92 non-null     str
 1   Order_Date     91 non-null     datetime64[us]
 2   Customer_Name  92 non-null     str
 3   City           92 non-null     str
 4   Category       92 non-null     str
 5   Product_Name   92 non-null     str
 6   Quantity       92 non-null     float64
 7   Discount       92 non-null     float64
 8   Sales          92 non-null     float64
 9   Payment_Mode   92 non-null     str
 10  Rating         92 non-null     float64
 11  Delivery_Days  92 non-null     float64
 12  Returned       92 non-null     str
dtypes: datetime64[us](1), float64(5), str(7)
memory usage: 14.0 KB

In [33]:
df.columns.to_list()

['Order_ID',
 'Order_Date',
 'Customer_Name',
 'City',
 'Category',
 'Product_Name',
 'Quantity',
 'Discount',
 'Sales',
 'Payment_Mode',
 'Rating',
 'Delivery_Days',
 'Returned']

In [34]:
df_clean.loc[df_clean['Quantity'] < 0, 'Quantity'] = np.nan

df_clean.loc[(df_clean['Discount'] < 0) | (df_clean['Discount'] > 1), 'Discount'] = np.nan

df_clean.loc[(df_clean['Rating'] < 0) | (df_clean['Rating'] > 5), 'Rating'] = np.nan

columns_to_fill = ["Quantity", "Discount", "Rating"]

for column in columns_to_fill:
    df_clean[column] = df_clean[column].fillna(df_clean[column].median())
print("INVALID VALUES HANDLED")

INVALID VALUES HANDLED

In [35]:
cols = ['Discount', 'Quantity', 'Sales', 'Rating']
for col in cols:
    
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_clean[(df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)]
    print(f"\n→ Found {len(outliers)} outliers in {col}")

→ Found 0 outliers in Discount

→ Found 1 outliers in Quantity

→ Found 12 outliers in Sales

→ Found 0 outliers in Rating

In [36]:
outlier_columns = ["Discount", "Rating", "Sales"]

for col in outlier_columns:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_clean[col] = df_clean[col].clip(
        lower=lower_bound,
        upper=upper_bound
    )

    outliers_after_capping = df_clean[
        (df_clean[col] < lower_bound) |
        (df_clean[col] > upper_bound)
    ]

    print(f"{col}: Outliers after capping = {len(outliers_after_capping)}")

Discount: Outliers after capping = 0
Rating: Outliers after capping = 0
Sales: Outliers after capping = 0

In [37]:
df_clean['Total_Amount'] = df_clean['Sales'] * df_clean['Quantity']

df_clean['Discount_Amount'] = df_clean['Total_Amount'] * df_clean['Discount']

df_clean['Final_Amount'] = df_clean['Total_Amount'] - df_clean['Discount_Amount']

df_clean['Order_Year'] = df_clean['Order_Date'].dt.year

df_clean['Order_Month'] = df_clean['Order_Date'].dt.month_name()

df_clean['Order_Day'] = df_clean['Order_Date'].dt.day_name()

In [38]:
df_clean.head(10)

,Order_ID,Order_Date,Customer_Name,City,Category,Product_Name,Quantity,Discount,Sales,Payment_Mode,Rating,Delivery_Days,Returned,Total_Amount,Discount_Amount,Final_Amount,Order_Year,Order_Month,Order_Day
0,ORD-1001,2024-11-03,Arjun,Chandigarh,Beauty,Moisturizer,1.0,0.25,111.7500,Upi,5.0,9.0,Yes,111.7500,27.937500,83.812500,2024.0,November,Sunday
1,ORD-1002,2024-01-24,Ritika,Chandigarh,Stationery,Stapler,1.0,0.00,799.0000,Net Banking,2.5,9.0,No,799.0000,0.000000,799.000000,2024.0,January,Wednesday
2,ORD-1003,2024-04-24,Kabir,Mohali,Beauty,Face Wash,7.0,0.05,11538.7125,Card,5.0,7.0,No,80770.9875,4038.549375,76732.438125,2024.0,April,Wednesday
3,ORD-1004,2024-01-27,Unknown,Jaipur,Furniture,Chair,4.0,0.10,716.4000,Cash,3.5,10.0,No,2865.6000,286.560000,2579.040000,2024.0,January,Saturday
4,ORD-1005,2024-01-21,Tanya,Mohali,Electronics,Power Bank,2.0,0.15,1698.3000,Cash,4.5,4.0,Yes,3396.6000,509.490000,2887.110000,2024.0,January,Sunday
5,ORD-1006,2024-01-21,Arjun,Mumbai,Electronics,Charger,4.0,0.10,11538.7125,Cash,4.0,6.0,No,46154.8500,4615.485000,41539.365000,2024.0,January,Sunday
6,ORD-1007,2024-09-03,Rahul,Bengaluru,Furniture,Desk,4.0,0.25,1797.0000,Card,3.0,8.0,No,7188.0000,1797.000000,5391.000000,2024.0,September,Tuesday
7,ORD-1008,2024-03-24,Neha,Chandigarh,Furniture,Chair,4.0,0.25,11538.7125,Cash,4.0,5.0,Yes,46154.8500,11538.712500,34616.137500,2024.0,March,Sunday
8,ORD-1009,2024-06-16,Rohit,Mohali,Clothing,Shirt,6.0,0.05,11538.7125,Card,3.5,3.0,No,69232.2750,3461.613750,65770.661250,2024.0,June,Sunday
9,ORD-1010,2024-05-29,Mehak,Jaipur,Beauty,Lip Balm,5.0,0.25,5621.2500,Card,3.0,9.0,No,28106.2500,7026.562500,21079.687500,2024.0,May,Wednesday

In [39]:
# What is the total sales amount?
print(f"Total Sales: Rs.{round(df_clean['Sales'].sum(),3)}")
# Which category has the highest total sales?
print(f"Highest sales category: {df_clean.groupby('Category')['Sales'].sum().idxmax()}")
# Which region has the highest sales?
print(f"Highest sales region: {df_clean.groupby('City')['Sales'].sum().idxmax()}")
# Which product has the highest quantity sold?
print(f"Highest Quantity sold Product: {df_clean.groupby('Product_Name')['Quantity'].sum().idxmax()}")
# What is the average rating?
print(f"Average Rating: {df_clean['Rating'].mean()}")
# Which payment method is used most?
print(f"Most used payment method: {df_clean['Payment_Mode'].value_counts().idxmax()}")
# Which month has the highest sales?
print(f"Month with highest sales: {df_clean.groupby('Order_Month')['Sales'].sum().idxmax()}")
# Find the top 5 highest sales records.
print(f"Highest Sales Record:")
display(df_clean.sort_values('Sales', ascending= False).head())
# Find the bottom 5 sales records.
print(f"Bottom Sales Record:")
display(df_clean.sort_values('Sales', ascending= True).head())
# Count the number of orders in each category.
print(f"Number of Orders in each category: {df_clean['Category'].value_counts()}")

Total Sales: Rs.324442.9
Highest sales category: Clothing
Highest sales region: Mohali
Highest Quantity sold Product: Charger
Average Rating: 3.717391304347826
Most used payment method: Card
Month with highest sales: January
Highest Sales Record:

,Order_ID,Order_Date,Customer_Name,City,Category,Product_Name,Quantity,Discount,Sales,Payment_Mode,Rating,Delivery_Days,Returned,Total_Amount,Discount_Amount,Final_Amount,Order_Year,Order_Month,Order_Day
2,ORD-1003,2024-04-24,Kabir,Mohali,Beauty,Face Wash,7.0,0.05,11538.7125,Card,5.0,7.0,No,80770.9875,4038.549375,76732.438125,2024.0,April,Wednesday
8,ORD-1009,2024-06-16,Rohit,Mohali,Clothing,Shirt,6.0,0.05,11538.7125,Card,3.5,3.0,No,69232.2750,3461.613750,65770.661250,2024.0,June,Sunday
7,ORD-1008,2024-03-24,Neha,Chandigarh,Furniture,Chair,4.0,0.25,11538.7125,Cash,4.0,5.0,Yes,46154.8500,11538.712500,34616.137500,2024.0,March,Sunday
5,ORD-1006,2024-01-21,Arjun,Mumbai,Electronics,Charger,4.0,0.10,11538.7125,Cash,4.0,6.0,No,46154.8500,4615.485000,41539.365000,2024.0,January,Sunday
18,ORD-1019,2024-01-05,Mehak,Chandigarh,Beauty,Face Wash,8.0,0.05,11538.7125,Upi,5.0,7.0,No,92309.7000,4615.485000,87694.215000,2024.0,January,Friday

Bottom Sales Record:

,Order_ID,Order_Date,Customer_Name,City,Category,Product_Name,Quantity,Discount,Sales,Payment_Mode,Rating,Delivery_Days,Returned,Total_Amount,Discount_Amount,Final_Amount,Order_Year,Order_Month,Order_Day
0,ORD-1001,2024-11-03,Arjun,Chandigarh,Beauty,Moisturizer,1.0,0.250,111.75,Upi,5.0,9.0,Yes,111.75,27.9375,83.8125,2024.0,November,Sunday
17,ORD-1018,2024-01-19,Sneha,Chandigarh,Clothing,Kurti,1.0,0.100,134.10,Cod,3.0,9.0,No,134.10,13.4100,120.6900,2024.0,January,Friday
13,ORD-1014,2024-03-23,Rohit,Delhi,Furniture,Chair,1.0,0.200,159.20,Cash,3.5,4.0,Yes,159.20,31.8400,127.3600,2024.0,March,Saturday
10,ORD-1011,2024-09-06,Priya,Jaipur,Electronics,Power Bank,2.0,0.050,188.10,Upi,4.0,7.0,No,376.20,18.8100,357.3900,2024.0,September,Friday
43,ORD-1044,2024-03-03,Rohit,Mumbai,Clothing,Shirt,1.0,0.125,199.00,Cod,5.0,10.0,No,199.00,24.8750,174.1250,2024.0,March,Sunday

Number of Orders in each category: Category
Furniture      20
Clothing       18
Electronics    16
Beauty         14
Stationery     12
Grocery        11
Clothng         1
Name: count, dtype: int64

In [40]:
# Total sales by category
print("Total sales by category:\n", df_clean.groupby('Category')['Sales'].sum())
# Total sales by region
print("\nTotal sales by region:\n", df_clean.groupby('City')['Sales'].sum())
# Average rating by category
print("\nAverage Rating by category:\n", df_clean.groupby('Category')['Rating'].mean())
# Total quantity sold by product
print("\nTotal quantity sold by product:\n", df_clean.groupby('Product_Name')['Quantity'].sum())
# Average final amount by payment method
print("\nAverage final amount by payment method:\n", df_clean.groupby('Payment_Mode')['Final_Amount'].mean())

Total sales by category:
 Category
Beauty         58906.5375
Clothing       64580.7875
Clothng          638.4000
Electronics    52781.5125
Furniture      59316.6375
Grocery        42923.5125
Stationery     45295.5125
Name: Sales, dtype: float64

Total sales by region:
 City
Bengaluru     39118.7125
Chandigarh    34738.6750
Delhi         37346.8125
Jaipur        47215.6250
Lucknow       18216.6500
Mohali        59746.1375
Mumbai        56424.6250
Pune          31635.6625
Name: Sales, dtype: float64

Average Rating by category:
 Category
Beauty         4.142857
Clothing       3.527778
Clothng        4.500000
Electronics    3.718750
Furniture      3.700000
Grocery        3.954545
Stationery     3.250000
Name: Rating, dtype: float64

Total quantity sold by product:
 Product_Name
Bookshelf       15.0
Chair           19.0
Charger        131.0
Cooking Oil     19.0
Desk            33.0
Face Wash       33.0
File Folder     17.0
Headphones       9.0
Jacket           4.0
Jeans           10.0
Keyboard        11.0
Kurti           10.0
Lip Balm        17.0
Marker           9.0
Moisturizer      1.0
Notebook        25.0
Pen Set         16.0
Power Bank      14.0
Serum            8.0
Shirt           37.0
Stapler          1.0
Stool           21.0
Sugar           25.0
Sunscreen        2.0
T-Shirt         18.0
Tea Pack         8.0
Wheat Flour      2.0
Name: Quantity, dtype: float64

Average final amount by payment method:
 Payment_Mode
Card           28518.793403
Cash           22915.806012
Cod            17431.385556
Net Banking    13180.948304
Upi             9171.882917
Name: Final_Amount, dtype: float64

In [41]:
df_clean.shape

(92, 19)

In [ ]:
output_file = "sales_data_cleaned.xlsx"
df_clean.to_excel(output_file, index=False)

print("Cleaned dataset saved as:", output_file)