## 🧪 Practice Tasks

Now it's YOUR turn! Try to solve these tasks using what you've learned.

<div style="padding: 12px; border-left: 5px solid #9C27B0; background-color: #f3e5f5; border-radius: 4px; margin: 10px 0;">
<strong>📝 Instructions:</strong> Write your code in the empty cells below each task. Try on your own first before looking at the solutions!
</div>

---

### Practice Task 1
**Display the first 10 rows of the dataset.**

In [1]:
import pandas as pd

In [4]:
df = pd.read_excel("DataSet_used\\sales_data_messy.xlsx")
df.head(10)

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800
3,TXN-1004,2026-01-15,Headphones,Accessories,150.0,1,150
4,TXN-1005,2026-01-11,Headphones,Accessories,150.0,4,600
5,TXN-1006,2026-01-08,Laptop,Electronics,1000.0,1,1000
6,TXN-1007,2026-01-29,Smartwatch,Accessories,200.0,1,200
7,TXN-1008,2026-01-21,Smartwatch,Accessories,200.0,2,400
8,TXN-1009,2026-01-07,Smartphone,Electronics,600.0,4,2400
9,TXN-1010,NaN,Smartwatch,Accessories,200.0,4,800

---

### Practice Task 2
**Find the total number of rows and columns in the dataset. Print them in this format:**
```
Rows: ___
Columns: ___
```

In [5]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 110
Columns: 7

---

### Practice Task 3
**Print all the unique values in the `Category` column and the `Product` column.**

In [12]:
print("Unique values in Category Column:", df['Category'].unique().tolist())
print()
print("Unique values in Product Column:", df['Product'].unique().tolist())

Unique values in Category Column: ['Accessories', 'Electronics', nan]

Unique values in Product Column: ['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet', nan]

---

### Practice Task 4
**Find out how many transactions happened for each product using `.value_counts()`.**

In [13]:

print(df['Product'].value_counts())

Product
Laptop        26
Headphones    24
Tablet        22
Smartwatch    19
Smartphone    15
Name: count, dtype: int64

---

### Practice Task 5
**What is the total revenue? What is the average revenue per transaction?**

In [22]:
# Your code here:
print(f"Total Revenue: {df['Revenue'].sum():,}")
print(f"Average Revenue: {round(df['Revenue'].mean(),2):,}")

Total Revenue: 151,550
Average Revenue: 1,377.73

---

### Practice Task 6
**Sort the dataset by `Price` in descending order and display the top 5 rows. Show only the `Product`, `Price`, and `Revenue` columns.**

In [23]:
df[['Product', 'Price', 'Revenue']].sort_values('Price', ascending= False).head(5)

   Product   Price  Revenue
5   Laptop  1000.0     1000
39     NaN  1000.0     4000
34  Laptop  1000.0     4000
29  Laptop  1000.0     4000
19  Laptop  1000.0     2000

---

### Practice Task 7
**Find the most common quantity purchased (which quantity appears most often).**

In [24]:
dic = df['Quantity'].value_counts().to_dict()
print("Value counts for Quantity:\n", dic)
l1 = list(dic.keys())
print("Most common quantity:",l1[0])

Value counts for Quantity:
 {1: 29, 4: 27, 3: 25, 2: 20, 5: 9}
Most common quantity: 1

---

### Practice Task 8
**Use `.describe()` with `include='all'` to get a summary of ALL columns (including text columns). What is the `top` (most frequent) product?**

In [25]:
df.describe()

             Price    Quantity      Revenue
count   107.000000  110.000000   110.000000
mean    487.850467    2.700000  1377.727273
std     332.999598    1.317142  1228.738190
min     150.000000    1.000000   150.000000
25%     200.000000    1.000000   450.000000
50%     400.000000    3.000000   900.000000
75%     800.000000    4.000000  2000.000000
max    1000.000000    5.000000  5000.000000

---

### Practice Task 9
**How many unique dates are in the dataset? Print the earliest and latest date.**

*Hint: Use `.nunique()`, `.min()`, and `.max()` on the Date column.*

In [31]:
import datetime

date = pd.to_datetime(df['Date'])
print("Unique Dates:",date.nunique())
print("Earliest Date:",date.min())
print("Latest Date:",date.max())

Unique Dates: 30
Earliest Date: 2026-01-01 00:00:00
Latest Date: 2026-01-31 00:00:00

---

### Practice Task 10
**Create a mini report that prints the following information:**
```
============ SALES REPORT ============
Total Transactions : ___
Total Products     : ___
Total Categories   : ___
Total Revenue      : ₹___
Average Revenue    : ₹___
Highest Revenue    : ₹___
Lowest Revenue     : ₹___
======================================
```

In [64]:
equal = '=' *20
print(f"{equal} SALES REPORT {equal}")
print("Total Transactions :", df.shape[0])
print("Total Products     :", df['Product'].value_counts().sum())
print("Total Categories   :", df['Category'].value_counts().sum())
print(f"Total Revenue      : ₹{df['Revenue'].sum():,}")
print(f"Average Revenue    : ₹{round(df['Revenue'].mean(),2):,}")
print(f"Highest Revenue    : ₹{df['Revenue'].max():,}")
print(f"Lowest Revenue     : ₹{df['Revenue'].min():,}")
print(f"{equal*3}")

==================== SALES REPORT ====================
Total Transactions : 110
Total Products     : 106
Total Categories   : 107
Total Revenue      : ₹151,550
Average Revenue    : ₹1,377.73
Highest Revenue    : ₹5,000
Lowest Revenue     : ₹150
============================================================

---

### ✅ Practice Task Solutions

<div style="padding: 12px; border-left: 5px solid #ff9800; background-color: #fff3e0; border-radius: 4px; margin: 10px 0;">
<strong>⚠️ Warning:</strong> Try to solve the tasks on your own FIRST! Only check the solutions after you've attempted them.
</div>

In [ ]:
# === SOLUTION: Task 1 ===
df.head(10)

In [ ]:
# === SOLUTION: Task 2 ===
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

In [ ]:
# === SOLUTION: Task 3 ===
print("Unique Categories:", df['Category'].unique())
print("Unique Products:", df['Product'].unique())

In [ ]:
# === SOLUTION: Task 4 ===
print(df['Product'].value_counts())

In [ ]:
# === SOLUTION: Task 5 ===
print("Total Revenue:", df['Revenue'].sum())
print("Average Revenue:", df['Revenue'].mean())

In [ ]:
# === SOLUTION: Task 6 ===
df.sort_values('Price', ascending=False)[['Product', 'Price', 'Revenue']].head()

In [ ]:
# === SOLUTION: Task 7 ===
print("Quantity distribution:")
print(df['Quantity'].value_counts())
print(f"\nMost common quantity: {df['Quantity'].value_counts().index[0]}")

In [ ]:
# === SOLUTION: Task 8 ===
print(df.describe(include='all'))

In [ ]:
# === SOLUTION: Task 9 ===
print("Number of unique dates:", df['Date'].nunique())
print("Earliest date:", df['Date'].min())
print("Latest date:", df['Date'].max())

In [ ]:
# === SOLUTION: Task 10 ===
print("============ SALES REPORT ============")
print(f"Total Transactions : {df.shape[0]}")
print(f"Total Products     : {df['Product'].nunique()}")
print(f"Total Categories   : {df['Category'].nunique()}")
print(f"Total Revenue      : ₹{df['Revenue'].sum():,}")
print(f"Average Revenue    : ₹{df['Revenue'].mean():,.0f}")
print(f"Highest Revenue    : ₹{df['Revenue'].max():,}")
print(f"Lowest Revenue     : ₹{df['Revenue'].min():,}")
print("======================================")

---

## 📝 Assignment

Complete the following assignment **after class**. Write your answers in the code cells provided.

---

### Assignment Question 1: Column Understanding

For each column in the dataset, write a comment explaining:
- What the column represents
- What data type it is
- One example value

Use `.head()` and `.dtypes` to figure this out.

In [67]:
df.head(5)

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800
3,TXN-1004,2026-01-15,Headphones,Accessories,150.0,1,150
4,TXN-1005,2026-01-11,Headphones,Accessories,150.0,4,600

In [68]:
df.dtypes

Transaction_ID        str
Date                  str
Product               str
Category              str
Price             float64
Quantity            int64
Revenue             int64
dtype: object

---

### Assignment Question 2: 5 Business Questions

Answer the following 5 questions using Pandas. Print the answer for each.

In [ ]:
# Q1: How many rows and columns are in the dataset?
df.shape

(110, 7)

In [77]:
# Q2: How many unique products and categories are there?
print(df['Product'].unique().tolist())
print(df['Category'].unique().tolist())

['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet', nan]
['Accessories', 'Electronics', nan]

In [84]:
# Q3: Which product has the highest number of transactions?
# Your code here:
high = df['Product'].value_counts().to_dict()
keys = list(high.keys())
print(keys[0])

Laptop

In [ ]:
# Q4: What is the total revenue and average revenue?
# Your code here:
print(f"Total Revenue      : ₹{df['Revenue'].sum():,}")
print(f"Average Revenue    : ₹{df['Revenue'].mean():,.0f}")

In [85]:
# Q5: Display the 3 transactions with the highest revenue.
# Your code here:
df.sort_values('Revenue', ascending= False).head(3)

   Transaction_ID        Date Product     Category   Price  Quantity  Revenue
26       TXN-1027  2026-01-06  Laptop  Electronics  1000.0         5     5000
21       TXN-1022  2026-01-21  Laptop  Electronics  1000.0         5     5000
20       TXN-1021  2026-01-22  Laptop  Electronics  1000.0         4     4000

---

### Assignment Question 3: Exploration Summary

Write a **complete exploration report** using Python. Your report should print:

1. Dataset shape
2. All column names
3. Data types of each column
4. Missing value count per column
5. Number of unique values per column
6. Statistical summary (describe)
7. Top product by transaction count
8. Top category by transaction count
9. Total, average, min, and max revenue

Format it neatly with section headers using `print()` statements.

In [103]:
# Your complete exploration report code here:
print(df.shape)
print(df.columns.to_list())
print(df.dtypes)
print(df.isnull().sum())
print(df.nunique())
print(df.describe())
print(df['Product'].value_counts().head(1))
print(df['Category'].value_counts().head(1))
print(df['Revenue'].sum())
print(df['Revenue'].mean())
print(df['Revenue'].min())
print(df['Revenue'].max())

(110, 7)
['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']
Transaction_ID        str
Date                  str
Product               str
Category              str
Price             float64
Quantity            int64
Revenue             int64
dtype: object
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64
Transaction_ID    97
Date              30
Product            5
Category           2
Price              5
Quantity           5
Revenue           17
dtype: int64
             Price    Quantity      Revenue
count   107.000000  110.000000   110.000000
mean    487.850467    2.700000  1377.727273
std     332.999598    1.317142  1228.738190
min     150.000000    1.000000   150.000000
25%     200.000000    1.000000   450.000000
50%     400.000000    3.000000   900.000000
75%     800.000000    4.000000  2000.000000
max    1000.000000    5.000000  5000.000000
Product
Laptop    26
Name: count, dtype: int64
Category
Electronics    64
Name: count, dtype: int64
151550
1377.7272727272727
150
5000

---

## 📌 Key Takeaways

Here's a summary of everything we learned today:

---

### 1. Loading Data
- Use `pd.read_excel()` for Excel files and `pd.read_csv()` for CSV files.
- The result is stored in a **DataFrame** (a table).

### 2. Viewing Data
| Method | What It Does |
| :--- | :--- |
| `.head(n)` | First `n` rows (default 5) |
| `.tail(n)` | Last `n` rows (default 5) |
| `.sample(n)` | `n` random rows |

### 3. Understanding Structure
| Method | What It Returns |
| :--- | :--- |
| `.shape` | (rows, columns) — **no parentheses!** |
| `.columns` | List of all column names |
| `.dtypes` | Data type of each column |
| `.info()` | Complete summary with types and null counts |

### 4. Statistical Summary
| Method | What It Returns |
| :--- | :--- |
| `.describe()` | Stats for numeric columns |
| `.describe(include='all')` | Stats for ALL columns |
| `.sum()` | Total of a column |
| `.mean()` | Average of a column |
| `.min()` / `.max()` | Smallest / Largest value |
| `.median()` | Middle value |

### 5. Exploring Values
| Method | What It Returns |
| :--- | :--- |
| `.unique()` | All distinct values |
| `.nunique()` | Count of distinct values |
| `.value_counts()` | Frequency of each value |
| `.isnull().sum()` | Count of missing values |

### 6. Sorting
- `.sort_values('column')` — ascending (default)
- `.sort_values('column', ascending=False)` — descending

### 7. Selecting Columns
- Single column: `df['Column']` → returns a **Series**
- Multiple columns: `df[['Col1', 'Col2']]` → returns a **DataFrame**

---

### 🎯 What's Next?

In the next lesson, we'll learn about **Data Selection & Filtering** — how to pick specific rows based on conditions (e.g., "Show me all Laptop transactions with revenue > ₹3000").

---

*Great job today! Data exploration is the foundation of every Data Science project. The better you understand your data, the better your analysis will be.* 🚀