# 📊 Data Exploration

---

**Project:** Retail Sales Analysis  
**Dataset:** `sales_data.xlsx` (100 transactions)   

---

> **What is Data Exploration?**  
> Before we analyze any data, we must first **understand** it. Data Exploration is the very first step in every Data Science project. Think of it like opening a new textbook — you first look at the table of contents, flip through the chapters, and get a feel for what's inside. That's exactly what we do with data!

---

## 🎯 Learning Objectives

1. **Load** a dataset into Python using Pandas.
2. **View** the first and last few rows of a dataset.
3. **Find** the total number of rows and columns.
4. **Check** the data type of each column.
5. **Get** a quick summary of the dataset using `.info()` and `.describe()`.
6. **Explore** individual columns — unique values, counts, and frequencies.
7. **Sort** data to find the highest and lowest values.
8. **Ask and answer** basic questions about the data.

---

## 📖 Concept Explanation

### Why do we explore data?

Imagine you're a store manager. Before making any business decisions, you'd want to know:
- How many transactions happened?
- What products were sold?
- What was the highest and lowest sale?
- Are there any missing entries in the records?

**Data Exploration** helps us answer these basic questions. It's like a health checkup for your data.

### What tools do we use?

We use a Python library called **Pandas**. Pandas gives us special functions (methods) to quickly explore any dataset:

| Method | What It Does |
| :--- | :--- |
| `.head()` | Shows the first 5 rows |
| `.tail()` | Shows the last 5 rows |
| `.shape` | Tells us (rows, columns) count |
| `.columns` | Lists all column names |
| `.dtypes` | Shows the data type of each column |
| `.info()` | Gives a complete summary (types + missing values) |
| `.describe()` | Gives statistics for number columns (mean, min, max, etc.) |
| `.value_counts()` | Counts how many times each value appears |
| `.unique()` | Shows all unique (distinct) values |
| `.nunique()` | Counts how many unique values exist |
| `.isnull().sum()` | Counts missing values in each column |
| `.sort_values()` | Sorts the data by a column |

### What is our dataset about?

We are using a **Sales Data** file (`sales_data.xlsx`) that contains 100 transactions from a retail store. Each row represents one transaction — what was sold, when, at what price, and how much revenue it generated.

---

## 💻 Code Examples

Let's go step by step. We will learn each method one at a time.

---

### Step 1: Import Pandas

In [4]:
# Step 1: Import the Pandas library
# 'pd' is a short nickname (alias) so we don't have to type 'pandas' every time
import pandas as pd

# Let's verify it loaded correctly by printing the version
print("Pandas version:", pd.__version__)

Pandas version: 3.0.2

**What happened?**  
- We imported the Pandas library and gave it a short name `pd`.  
- Now we can use `pd.` to access all Pandas functions.

---

### Step 2: Load the Dataset

In [8]:
# Step 2: Load the Excel file into a DataFrame
# A DataFrame is like a table (rows and columns) in Python
# We use pd.read_excel() because our file is an Excel file (.xlsx)
df = pd.read_excel('DataSet_used\\sales_data_messy.xlsx')

# 'df' is a common short name for DataFrame
# Let's confirm the data loaded by checking its type
print("Type of df:", type(df))

Type of df: <class 'pandas.DataFrame'>

**What happened?**  
- `pd.read_excel('sales_data.xlsx')` reads the Excel file and creates a **DataFrame** (a table).  
- We stored this table in a variable called `df`.  
- The output confirms it's a `pandas.DataFrame`.

<div style="padding: 12px; border-left: 5px solid #2196F3; background-color: #e3f2fd; border-radius: 4px; margin: 10px 0;">
<strong>💡 Note:</strong> If the file was a CSV, we would use <code>pd.read_csv('filename.csv')</code> instead.
</div>

---

### Step 3: View the First Few Rows — `.head()`

In [ ]:
# Step 3: Look at the first 5 rows of the dataset
# .head() shows the TOP 5 rows by default
df.head(10)

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800
3,TXN-1004,2026-01-15,Headphones,Accessories,150.0,1,150
4,TXN-1005,2026-01-11,Headphones,Accessories,150.0,4,600
5,TXN-1006,2026-01-08,Laptop,Electronics,1000.0,1,1000
6,TXN-1007,2026-01-29,Smartwatch,Accessories,200.0,1,200
7,TXN-1008,2026-01-21,Smartwatch,Accessories,200.0,2,400
8,TXN-1009,2026-01-07,Smartphone,Electronics,600.0,4,2400
9,TXN-1010,NaN,Smartwatch,Accessories,200.0,4,800

**What happened?**  
- `.head()` displays the first 5 rows of our data.
- This gives us a quick preview — we can see the column names and what kind of data is in each column.

**Expected Output:**

| | Transaction_ID | Date | Product | Category | Price | Quantity | Revenue |
|---|---|---|---|---|---|---|---|
| 0 | TXN-1001 | 2026-01-07 | Headphones | Accessories | 150 | 2 | 300 |
| 1 | TXN-1002 | 2026-01-20 | Smartphone | Electronics | 600 | 4 | 2400 |
| 2 | TXN-1003 | 2026-01-29 | Smartphone | Electronics | 600 | 3 | 1800 |
| 3 | TXN-1004 | 2026-01-15 | Headphones | Accessories | 150 | 1 | 150 |
| 4 | TXN-1005 | 2026-01-11 | Headphones | Accessories | 150 | 4 | 600 |

In [ ]:
# You can also pass a number to .head() to see more or fewer rows
# Let's see the first 3 rows
df.head(3)

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800

---

### Step 4: View the Last Few Rows — `.tail()`

In [ ]:
# Step 4: Look at the LAST 5 rows of the dataset
# .tail() shows the BOTTOM 5 rows by default
df.tail(10)

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
100,TXN-1084,2026-01-14,Smartphone,Electronics,600.0,4,2400
101,TXN-1054,2026-01-20,Laptop,Electronics,1000.0,1,1000
102,TXN-1071,2026-01-26,Tablet,Electronics,400.0,2,800
103,TXN-1046,2026-01-15,Laptop,Electronics,1000.0,3,3000
104,TXN-1045,2026-01-16,Tablet,Electronics,400.0,4,1600
105,TXN-1040,2026-01-27,NaN,Electronics,1000.0,4,4000
106,TXN-1023,2026-01-02,Laptop,Electronics,1000.0,1,1000
107,TXN-1081,2026-01-08,Headphones,Accessories,150.0,3,450
108,TXN-1011,2026-01-19,Smartphone,Electronics,600.0,2,1200
109,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300

**What happened?**  
- `.tail()` shows the last 5 rows.
- This is useful to check if the data ends properly (no garbage rows at the bottom).

**Expected Output:**

| | Transaction_ID | Date | Product | Category | Price | Quantity | Revenue |
|---|---|---|---|---|---|---|---|
| 95 | TXN-1096 | 2026-01-22 | Tablet | Electronics | 400 | 2 | 800 |
| 96 | TXN-1097 | 2026-01-29 | Laptop | Electronics | 1000 | 3 | 3000 |
| 97 | TXN-1098 | 2026-01-31 | Smartwatch | Accessories | 200 | 5 | 1000 |
| 98 | TXN-1099 | 2026-01-18 | Laptop | Electronics | 1000 | 1 | 1000 |
| 99 | TXN-1100 | 2026-01-26 | Tablet | Electronics | 400 | 4 | 1600 |

---

### Step 5: Check the Shape — `.shape`

In [9]:
# Step 5: Find the total number of rows and columns
# .shape returns a tuple: (number_of_rows, number_of_columns)
print("Shape of the dataset:", df.shape)

Shape of the dataset: (110, 7)

In [10]:
# We can also access rows and columns separately
print("Total Rows:", df.shape[0])        # First value = rows
print("Total Columns:", df.shape[1])     # Second value = columns

Total Rows: 110
Total Columns: 7

**What happened?**  
- `.shape` tells us the dataset has **100 rows** and **7 columns**.
- This means we have 100 transactions and 7 pieces of information about each transaction.

**Expected Output:**
```
Shape of the dataset: (100, 7)
Total Rows: 100
Total Columns: 7
```

<div style="padding: 12px; border-left: 5px solid #8f877d; background-color: #575047; border-radius: 4px; margin: 10px 0;">
<strong>⚠️ Notice:</strong> <code>.shape</code> has NO parentheses <code>()</code>. It is a <strong>property</strong>, not a method. Writing <code>.shape()</code> will give an error!
</div>

---

### Step 6: Check Column Names — `.columns`

In [11]:
# Step 6: See all the column names in the dataset
# .columns lists every column name
print("Column Names:")
print(df.columns)

Column Names:
Index(['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity',
       'Revenue'],
      dtype='str')

In [12]:
# To get column names as a simple Python list:
column_list = df.columns.tolist()
print("Columns as a list:", column_list)

Columns as a list: ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']

**What happened?**  
- `.columns` gives us all 7 column names: `Transaction_ID`, `Date`, `Product`, `Category`, `Price`, `Quantity`, `Revenue`.
- `.tolist()` converts it to a regular Python list for easier reading.

**Expected Output:**
```
Columns as a list: ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']
```

---

### Step 7: Check Data Types — `.dtypes`

In [13]:
# Step 7: Check the data type of each column
# Data type tells us what kind of data each column holds:
#   - 'object' or 'str' = text (strings)
#   - 'int64'           = whole numbers (integers)
#   - 'float64'         = decimal numbers
#   - 'datetime64'      = dates
print("Data Types:")
print(df.dtypes)

Data Types:
Transaction_ID        str
Date                  str
Product               str
Category              str
Price             float64
Quantity            int64
Revenue             int64
dtype: object

**What happened?**  
- `Transaction_ID`, `Date`, `Product`, `Category` are **text** (string/object type).
- `Price`, `Quantity`, `Revenue` are **numbers** (int64 = whole numbers).

**Expected Output:**
```
Transaction_ID     str
Date               str
Product            str
Category           str
Price            int64
Quantity         int64
Revenue          int64
```

<div style="padding: 12px; border-left: 5px solid #4CAF50; background-color: #e8f5e9; border-radius: 4px; margin: 10px 0;">
<strong>🤔 Think About It:</strong> The <code>Date</code> column shows as <code>str</code> (text), not as a date type. This means Pandas is treating dates as plain text. In a future lesson, we'll learn how to convert it to a proper date format.
</div>

---

### Step 8: Get Complete Summary — `.info()`

In [ ]:
# Step 8: Get a complete overview of the dataset
# .info() gives us:
#   - Total number of rows (entries)
#   - Column names
#   - How many non-null (non-empty) values each column has
#   - Data type of each column
#   - Memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  107 non-null    str
 1   Date            107 non-null    str
 2   Product         106 non-null    str
 3   Category        107 non-null    str
 4   Price           107 non-null    float64
 5   Quantity        110 non-null    int64
 6   Revenue         110 non-null    int64
dtypes: float64(1), int64(2), str(4)
memory usage: 6.1 KB

**What happened?**  
- `.info()` is like a **health report** of our dataset.
- It tells us:
  - We have **100 entries** (rows 0 to 99).
  - All 7 columns have **100 non-null values** — meaning **no data is missing**! ✅
  - Memory usage is very small (about 5.6 KB).

**Expected Output:**
```
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  100 non-null    str  
 1   Date            100 non-null    str  
 2   Product         100 non-null    str  
 3   Category        100 non-null    str  
 4   Price           100 non-null    int64
 5   Quantity        100 non-null    int64
 6   Revenue         100 non-null    int64
memory usage: 5.6 KB
```

---

### Step 9: Get Statistical Summary — `.describe()`

In [ ]:
# Step 9: Get statistics for all NUMERIC columns
# .describe() calculates:
#   - count : how many values
#   - mean  : average value
#   - std   : standard deviation (how spread out values are)
#   - min   : smallest value
#   - 25%   : value below which 25% of data falls
#   - 50%   : middle value (median)
#   - 75%   : value below which 75% of data falls
#   - max   : largest value
df.describe()

             Price    Quantity      Revenue
count   107.000000  110.000000   110.000000
mean    487.850467    2.700000  1377.727273
std     332.999598    1.317142  1228.738190
min     150.000000    1.000000   150.000000
25%     200.000000    1.000000   450.000000
50%     400.000000    3.000000   900.000000
75%     800.000000    4.000000  2000.000000
max    1000.000000    5.000000  5000.000000

**What happened?**  
- `.describe()` only works on **numeric columns** (Price, Quantity, Revenue).
- We can instantly see:
  - **Average price** is ₹481
  - **Minimum revenue** is ₹150, **maximum** is ₹5,000
  - **Average quantity** per transaction is about 2.7 items
  - The **median (50%) price** is ₹400

**Expected Output:**

| | Price | Quantity | Revenue |
|---|---|---|---|
| count | 100.00 | 100.00 | 100.00 |
| mean | 481.00 | 2.71 | 1358.00 |
| std | 333.92 | 1.34 | 1236.05 |
| min | 150.00 | 1.00 | 150.00 |
| 25% | 200.00 | 1.00 | 450.00 |
| 50% | 400.00 | 3.00 | 800.00 |
| 75% | 700.00 | 4.00 | 2000.00 |
| max | 1000.00 | 5.00 | 5000.00 |

---

### Step 10: Check for Missing Values — `.isnull().sum()`

In [ ]:
# Step 10: Check if any column has missing (empty/NaN) values
# .isnull() marks every cell as True (if missing) or False (if present)
# .sum() adds up all the True values for each column
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Transaction_ID    3
Date              3
Product           4
Category          3
Price             3
Quantity          0
Revenue           0
dtype: int64

In [ ]:
# We can also check the total number of missing values in the entire dataset
total_missing = df.isnull().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 16

**What happened?**  
- Every column shows **0** missing values.
- This means our dataset is **complete** — no gaps! 🎉
- In real-world data, you'll often find missing values. We'll learn how to handle them in a future lesson.

**Expected Output:**
```
Missing values in each column:
Transaction_ID    0
Date              0
Product           0
Category          0
Price             0
Quantity          0
Revenue           0
dtype: int64

Total missing values in the dataset: 0
```

---

### Step 11: Explore Unique Values — `.unique()` and `.nunique()`

In [15]:
# Step 11a: See all unique (distinct) products in the dataset
# .unique() returns an array of all distinct values in a column
print("Unique Products:")
print(df['Product'].unique())
print(df['Category'].unique())

Unique Products:
<StringArray>
['Headphones', 'Smartphone', 'Laptop', 'Smartwatch', 'Tablet', nan]
Length: 6, dtype: str
<StringArray>
['Accessories', 'Electronics', nan]
Length: 3, dtype: str

In [ ]:
# Step 11b: Count HOW MANY unique values each column has
# .nunique() returns just the count (a single number)
print("Number of unique products:", df['Product'].nunique())
print("Number of unique categories:", df['Category'].nunique())
print("Number of unique dates:", df['Date'].nunique())

Number of unique products: 5
Number of unique categories: 2
Number of unique dates: 30

In [ ]:
# We can also check unique values for all columns at once
print("Unique value count per column:")
print(df.nunique())

Unique value count per column:
Transaction_ID    97
Date              30
Product            5
Category           2
Price              5
Quantity           5
Revenue           17
dtype: int64

**What happened?**  
- There are **5 unique products**: Headphones, Smartphone, Laptop, Smartwatch, Tablet.
- There are **2 categories**: Accessories and Electronics.
- There are **30 unique dates** — data spans across almost all days of January 2026.
- Each `Transaction_ID` is unique (100 unique out of 100 rows) — good, no duplicates!

**Expected Output:**
```
Unique Products: ['Headphones' 'Smartphone' 'Laptop' 'Smartwatch' 'Tablet']
Number of unique products: 5
Number of unique categories: 2
Number of unique dates: 30
```

---

### Step 12: Count Values — `.value_counts()`

In [ ]:
# Step 12a: Count how many times each product appears
# .value_counts() counts the frequency of each value and sorts from highest to lowest
print("Product frequency:")
print(df[['Product']].value_counts())

Product frequency:
Product
Laptop        26
Headphones    24
Tablet        22
Smartwatch    19
Smartphone    15
Name: count, dtype: int64

In [ ]:
# Step 12b: Count how many transactions belong to each category
print("Category frequency:")
print(df['Category'].value_counts())

Category frequency:
Category
Electronics    64
Accessories    43
Name: count, dtype: int64

In [ ]:
# Step 12c: Count quantity distribution
# How many transactions had quantity 1, 2, 3, 4, or 5?
print("Quantity distribution:")
print(df['Quantity'].value_counts())

Quantity distribution:
Quantity
1    29
4    27
3    25
2    20
5     9
Name: count, dtype: int64

**What happened?**  
- **Laptop** is the most sold product (25 transactions), followed by **Headphones** (22).
- **Electronics** category has more transactions (58) than **Accessories** (42).
- `.value_counts()` automatically sorts from most frequent to least frequent.

**Expected Output:**
```
Product frequency:
Product
Laptop        25
Headphones    22
Smartwatch    20
Tablet        20
Smartphone    13
Name: count, dtype: int64
```

---

### Step 13: Basic Column Statistics

In [ ]:
# Step 13: Get individual statistics for specific columns

# Total revenue across all transactions
print("Total Revenue:", df['Revenue'].sum())

# Average (mean) price
print("Average Price:", df['Price'].mean())

# Highest revenue in a single transaction
print("Maximum Revenue:", df['Revenue'].max())

# Lowest revenue in a single transaction
print("Minimum Revenue:", df['Revenue'].min())

# Middle value (median) of quantity
print("Median Quantity:", df['Quantity'].median())

Total Revenue: 151550
Average Price: 487.85046728971963
Maximum Revenue: 5000
Minimum Revenue: 150
Median Quantity: 3.0

**What happened?**  
- The store earned a **total revenue of ₹1,35,800** from 100 transactions.
- The **average product price** is ₹481.
- The **highest single transaction** generated ₹5,000 and the **lowest** was ₹150.

**Expected Output:**
```
Total Revenue: 135800
Average Price: 481.0
Maximum Revenue: 5000
Minimum Revenue: 150
Median Quantity: 3.0
```

---

### Step 14: Sorting Data — `.sort_values()`

In [17]:
# Step 14a: Sort by Revenue — highest first (descending)
# ascending=False means highest value comes first
print("Top 5 transactions by Revenue:")
df.sort_values('Price', ascending=False).head()

Top 5 transactions by Revenue:

   Transaction_ID        Date Product     Category   Price  Quantity  Revenue
5        TXN-1006  2026-01-08  Laptop  Electronics  1000.0         1     1000
39       TXN-1040  2026-01-27     NaN  Electronics  1000.0         4     4000
34       TXN-1035  2026-01-29  Laptop  Electronics  1000.0         4     4000
29       TXN-1030  2026-01-21  Laptop  Electronics  1000.0         4     4000
19       TXN-1020  2026-01-03  Laptop  Electronics  1000.0         2     2000

In [ ]:
# Step 14b: Sort by Revenue — lowest first (ascending)
# ascending=True is the default, so we don't even need to write it
print("Bottom 5 transactions by Revenue:")
df.sort_values('Revenue', ascending=True).head()

In [ ]:
# Step 14c: Sort by Price first, then by Quantity (both descending)
# When two rows have the same price, they are sorted by quantity
print("Sorted by Price (desc), then Quantity (desc):")
df.sort_values(['Price', 'Quantity'], ascending=[False, True]).head(10)

Sorted by Price (desc), then Quantity (desc):

    Transaction_ID        Date Product     Category   Price  Quantity  Revenue
5         TXN-1006  2026-01-08  Laptop  Electronics  1000.0         1     1000
22        TXN-1023  2026-01-02  Laptop  Electronics  1000.0         1     1000
53        TXN-1054  2026-01-20  Laptop  Electronics  1000.0         1     1000
59        TXN-1060  2026-01-21  Laptop  Electronics  1000.0         1     1000
85        TXN-1086  2026-01-04  Laptop  Electronics  1000.0         1     1000
98        TXN-1099  2026-01-18     NaN  Electronics  1000.0         1     1000
101       TXN-1054  2026-01-20  Laptop  Electronics  1000.0         1     1000
106       TXN-1023  2026-01-02  Laptop  Electronics  1000.0         1     1000
19        TXN-1020  2026-01-03  Laptop  Electronics  1000.0         2     2000
93        TXN-1094  2026-01-10  Laptop  Electronics  1000.0         2     2000

**What happened?**  
- The **highest revenue transaction** was ₹5,000 (a Laptop sold with quantity 5).
- The **lowest revenue transaction** was ₹150 (Headphones, quantity 1).
- We can sort by **multiple columns** by passing a list.

---

### Step 15: Selecting a Single Column

In [ ]:
# Step 15a: Select a single column using bracket notation
# This returns a Series (one-dimensional, like a single column)
product_column = df['Product']
print("Type:", type(product_column))
print(product_column.head())

Type: <class 'pandas.Series'>
0    Headphones
1    Smartphone
2    Smartphone
3    Headphones
4    Headphones
Name: Product, dtype: str

In [ ]:
# Step 15b: Select multiple columns using double brackets
# This returns a DataFrame (two-dimensional, like a mini table)
subset = df[['Product', 'Price', 'Revenue']]
print("Type:", type(subset))
print(subset.head())

Type: <class 'pandas.DataFrame'>
      Product  Price  Revenue
0  Headphones  150.0      300
1  Smartphone  600.0     2400
2  Smartphone  600.0     1800
3  Headphones  150.0      150
4  Headphones  150.0      600

**What happened?**  
- Single brackets `df['Product']` returns a **Series** (1 column).
- Double brackets `df[['Product', 'Price', 'Revenue']]` returns a **DataFrame** (multiple columns).

---

### Step 16: Quick Data Sample — `.sample()`

In [ ]:
# Step 16: View random rows from the dataset
# .sample() picks random rows each time you run it
# n=5 means pick 5 random rows
print("5 random rows:")
df.sample(5)

5 random rows:

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
89,TXN-1090,2026-01-02,Tablet,Electronics,400.0,1,400
43,TXN-1044,2026-01-28,Tablet,Electronics,400.0,4,1600
42,TXN-1043,2026-01-28,Headphones,Accessories,150.0,3,450
28,TXN-1029,2026-01-28,Tablet,Electronics,400.0,2,800
23,TXN-1024,2026-01-24,Headphones,Accessories,150.0,1,150

**What happened?**  
- `.sample(n=5)` picks 5 **random** rows from the dataset.
- Every time you run this cell, you'll get **different rows**!
- This is useful to get a general feel of the data beyond just the top and bottom rows.

---

## 🏗️ Project Application

Now let's put everything together and explore our Sales dataset like a **real data analyst** would. We'll answer meaningful business questions.

---

### Task 1: Dataset Overview Report

In [ ]:
# === DATASET OVERVIEW REPORT ===

# 1. How big is our dataset?
print("=" * 50)
print("         DATASET OVERVIEW REPORT")
print("=" * 50)
print(f"Total Transactions : {df.shape[0]}")
print(f"Total Columns      : {df.shape[1]}")
print(f"Column Names       : {df.columns.tolist()}")
print(f"Missing Values     : {df.isnull().sum().sum()}")
print("=" * 50)

**Expected Output:**
```
==================================================
         DATASET OVERVIEW REPORT
==================================================
Total Transactions : 100
Total Columns      : 7
Column Names       : ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']
Missing Values     : 0
==================================================
```

---

### Task 2: Product Analysis

In [ ]:
# === PRODUCT ANALYSIS ===

# How many unique products do we sell?
print("Number of unique products:", df['Product'].nunique())
print()

# What are those products?
print("Products available:")
print(df['Product'].unique())
print()

# Which product was sold the most (by number of transactions)?
print("Product Transaction Counts:")
print(df['Product'].value_counts())
print()

# Which product was sold the MOST?
most_sold = df['Product'].value_counts().index[0]
most_sold_count = df['Product'].value_counts().values[0]
print(f"Most sold product: {most_sold} ({most_sold_count} transactions)")

# Which product was sold the LEAST?
least_sold = df['Product'].value_counts().index[-1]
least_sold_count = df['Product'].value_counts().values[-1]
print(f"Least sold product: {least_sold} ({least_sold_count} transactions)")

**Expected Output:**
```
Number of unique products: 5

Products available:
['Headphones' 'Smartphone' 'Laptop' 'Smartwatch' 'Tablet']

Product Transaction Counts:
Product
Laptop        25
Headphones    22
Smartwatch    20
Tablet        20
Smartphone    13
Name: count, dtype: int64

Most sold product: Laptop (25 transactions)
Least sold product: Smartphone (13 transactions)
```

---

### Task 3: Category Exploration

In [ ]:
# === CATEGORY EXPLORATION ===

# What categories exist in our store?
print("Unique Categories:", df['Category'].unique())
print()

# How many transactions per category?
print("Transactions per Category:")
print(df['Category'].value_counts())
print()

# What percentage of transactions belong to each category?
print("Category Percentage:")
print(df['Category'].value_counts(normalize=True) * 100)

**What we learned:**  
- **Electronics** dominates with **58% of transactions**.
- **Accessories** make up the remaining **42%**.

**Expected Output:**
```
Unique Categories: ['Accessories' 'Electronics']

Transactions per Category:
Category
Electronics    58
Accessories    42
Name: count, dtype: int64

Category Percentage:
Category
Electronics    58.0
Accessories    42.0
Name: proportion, dtype: float64
```

---

### Task 4: Revenue Insights

In [20]:
# === REVENUE INSIGHTS ===

print("=" * 40)
print("       REVENUE INSIGHTS")
print("=" * 40)

# Total revenue earned
print(f"Total Revenue     : ₹{df['Revenue'].sum():,}")

# Average revenue per transaction
print(f"Average Revenue   : ₹{df['Revenue'].mean():,.0f}")

# Highest single transaction
print(f"Highest Revenue   : ₹{df['Revenue'].max():,}")

# Lowest single transaction
print(f"Lowest Revenue    : ₹{df['Revenue'].min():,}")

# Median revenue (middle value)
print(f"Median Revenue    : ₹{df['Revenue'].median():,.0f}")

print("=" * 40)

========================================
       REVENUE INSIGHTS
========================================
Total Revenue     : ₹151,550
Average Revenue   : ₹1,378
Highest Revenue   : ₹5,000
Lowest Revenue    : ₹150
Median Revenue    : ₹900
========================================

**Expected Output:**
```
========================================
       REVENUE INSIGHTS
========================================
Total Revenue     : ₹135,800
Average Revenue   : ₹1,358
Highest Revenue   : ₹5,000
Lowest Revenue    : ₹150
Median Revenue    : ₹800
========================================
```

---

### Task 5: Top and Bottom Transactions

In [22]:
# === TOP 5 HIGHEST REVENUE TRANSACTIONS ===

# Sort by Revenue in descending order and show top 5
print("Top 5 Highest Revenue Transactions:")
print("-" * 40)
top_5 = df.sort_values('Revenue', ascending=False).head()
print(top_5[['Transaction_ID', 'Product', 'Quantity', 'Revenue']])

Top 5 Highest Revenue Transactions:
----------------------------------------
   Transaction_ID Product  Quantity  Revenue
26       TXN-1027  Laptop         5     5000
21       TXN-1022  Laptop         5     5000
20       TXN-1021  Laptop         4     4000
29       TXN-1030  Laptop         4     4000
34       TXN-1035  Laptop         4     4000

In [21]:
# === BOTTOM 5 LOWEST REVENUE TRANSACTIONS ===

# Sort by Revenue in ascending order and show bottom 5
print("Bottom 5 Lowest Revenue Transactions:")
print("-" * 40)
bottom_5 = df.sort_values('Revenue', ascending=True).head()
print(bottom_5[['Transaction_ID', 'Product', 'Quantity', 'Revenue']])

Bottom 5 Lowest Revenue Transactions:
----------------------------------------
   Transaction_ID     Product  Quantity  Revenue
3        TXN-1004  Headphones         1      150
14       TXN-1015  Headphones         1      150
12       TXN-1013  Headphones         1      150
23       TXN-1024  Headphones         1      150
60       TXN-1061  Headphones         1      150

**What we learned:**  
- The **highest revenue** comes from **Laptop** transactions (₹5,000 = ₹1,000 × 5 units).
- The **lowest revenue** comes from **Headphones** bought in single quantity (₹150 × 1).

---

### Task 6: Price Analysis

In [ ]:
# === PRICE ANALYSIS ===

# What are the different price points?
print("Unique Prices:")
print(sorted(df['Price'].unique()))
print()

# How many transactions at each price point?
print("Transactions at each Price Point:")
print(df['Price'].value_counts().sort_index())
print()

# Cheapest and most expensive products
print(f"Cheapest product price  : ₹{df['Price'].min()}")
print(f"Most expensive product  : ₹{df['Price'].max()}")

**What we learned:**  
- There are **5 price points**: ₹150, ₹200, ₹400, ₹600, ₹1,000.
- Each price corresponds to a specific product.
- Using `.sort_index()` after `.value_counts()` sorts by the price value instead of frequency.

---

## ⚠️ Common Mistakes

Here are the most common mistakes beginners make during data exploration — and how to fix them.

---

### Mistake 1: Using parentheses with `.shape`

In [ ]:
# ❌ WRONG — .shape is NOT a method, it's a property
# df.shape()   # This will cause: TypeError: 'tuple' object is not callable

# ✅ CORRECT — use .shape without parentheses
print("Correct way:", df.shape)

---

### Mistake 2: Wrong column name (case-sensitive!)

In [ ]:
# ❌ WRONG — Python is case-sensitive!
# df['product']   # KeyError: 'product'
# df['PRODUCT']   # KeyError: 'PRODUCT'
# df['revenue']   # KeyError: 'revenue'

# ✅ CORRECT — Use the exact column name as it appears in the dataset
print("Correct:", df['Product'].head(3).tolist())    # Capital 'P'
print("Correct:", df['Revenue'].head(3).tolist())    # Capital 'R'

<div style="padding: 12px; border-left: 5px solid #4CAF50; background-color: #e8f5e9; border-radius: 4px; margin: 10px 0;">
<strong>💡 Tip:</strong> If you're unsure of the exact column name, always check with <code>df.columns</code> first!
</div>

---

### Mistake 3: Single brackets vs Double brackets

In [ ]:
# ❌ WRONG — Using single brackets to select multiple columns
# df['Product', 'Price']   # KeyError: ('Product', 'Price')

# ✅ CORRECT — Use double brackets (a list inside brackets)
print("Correct way to select multiple columns:")
print(df[['Product', 'Price']].head(3))

---

### Mistake 4: Forgetting parentheses with methods

In [ ]:
# ❌ WRONG — Forgetting () with methods
# This doesn't CALL the function — it just shows the function object
print("Without ():", df['Revenue'].sum)  # Shows <bound method ...>
print()

# ✅ CORRECT — Add () to actually call the function
print("With ():", df['Revenue'].sum())   # Shows 135800

---

### Mistake 5: Using `.describe()` and expecting text columns

In [ ]:
# ❌ INCOMPLETE — .describe() by default only shows numeric columns
# It will NOT show Product, Category, etc.
print("Default describe (numeric only):")
print(df.describe())
print()

# ✅ FIX — Use include='all' to see ALL columns including text
print("Describe ALL columns:")
print(df.describe(include='all'))

**What happened?**  
- With `include='all'`, we also see stats for text columns:
  - `count` — number of non-null values
  - `unique` — number of unique values
  - `top` — most frequent value
  - `freq` — how many times the most frequent value appears

---

### Mistake 6: Confusing `.count()` with `.shape[0]`

In [ ]:
# Both give the same answer HERE because there are no missing values.
# But they work differently!

# .shape[0] — Always gives total number of rows (including empty ones)
print("shape[0]:", df.shape[0])           # Always 100

# .count() — Gives number of NON-MISSING values per column
print("\ncount():")
print(df.count())

# When there are missing values, .count() will show LESS than .shape[0]
# We'll see this in the data cleaning lesson!

---