In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("Superstore_Messy.csv")

# *Data Exploration*

In [19]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [20]:
# How many rows and columns are present in the dataset?
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10044
Columns: 21

In [21]:
print(df.columns.to_list())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [22]:
print(df.dtypes)

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10044 entries, 0 to 10043
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10044 non-null  int64
 1   Order ID       10044 non-null  str
 2   Order Date     10044 non-null  str
 3   Ship Date      10044 non-null  str
 4   Ship Mode      10044 non-null  str
 5   Customer ID    10044 non-null  str
 6   Customer Name  10004 non-null  str
 7   Segment        10044 non-null  str
 8   Country        10044 non-null  str
 9   City           10044 non-null  str
 10  State          10044 non-null  str
 11  Postal Code    10004 non-null  float64
 12  Region         10044 non-null  str
 13  Product ID     10044 non-null  str
 14  Category       10044 non-null  str
 15  Sub-Category   10044 non-null  str
 16  Product Name   10044 non-null  str
 17  Sales          10004 non-null  float64
 18  Quantity       10044 non-null  int64
 19  Discount       10044 non-null  float64
 20  Profit         10004 non-null  float64
dtypes: float64(4), int64(2), str(15)
memory usage: 3.4 MB

In [24]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,10044.000000,10004.000000,10004.000000,10044.000000,10044.000000,10004.000000
mean,4994.465253,55154.199320,255.108238,3.790422,0.156261,28.667871
std,2885.342882,32037.893863,1702.917481,2.224568,0.206516,233.940828
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2497.750000,23223.000000,17.332500,2.000000,0.000000,1.713750
50%,4989.500000,55901.000000,54.780000,3.000000,0.200000,8.636000
75%,7492.250000,90008.000000,209.970000,5.000000,0.200000,29.331600
max,9994.000000,99301.000000,121504.000000,14.000000,0.800000,8399.976000

In [25]:
# How many unique categories are there?
print(df['Category'].unique().tolist())
print("Total Unique Categories:", df['Category'].nunique())

['Furniture', 'Office Supplies', 'Technology', 'office supplies', 'technology', 'furniture']
Total Unique Categories: 6

In [26]:
print(df['Sub-Category'].unique().tolist())

['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage', 'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper', 'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines', 'Copiers']

In [27]:
print(df['Segment'].unique().tolist())

['Consumer', 'Corporate', 'Home Office']

In [28]:
print(df['Region'].unique().tolist())
# Which region appears most frequently?
freq = list(df['Region'].value_counts().to_dict())
print("Most frequent Region :",freq[0])

['South', 'West', 'Central', 'East']
Most frequent Region : West

In [29]:
# What is the total sales amount?
print(f"Rs {df['Sales'].sum():,}")

Rs 2,552,102.8118999996

In [30]:
# Which category has the highest sales?
# print(df.groupby("Category")["Sales"].sum().idxmax())
print(df.groupby("Category")["Sales"].sum().sort_values(ascending=False).index[0])

Technology

# *Data Qulaity Assessment*

In [46]:
print("Total Missing Values in dataset before cleaning:", df.isnull().sum().sum())
missing = df.isnull().sum()
print("\nMissing Values with respect to columns:\n",missing[missing>0])

Total Missing Values in dataset before cleaning: 160

Missing Values with respect to columns:
 Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64

In [32]:
print("Total Duplicate Rows in dataset:", df.duplicated().sum())
print("\nSome duplicate rows in dataset:\n\n")
df[df.duplicated()].head(5)

Total Duplicate Rows in dataset:

 48

Some duplicate rows in dataset:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9994,3126,CA-2015-121720,06-11-2015,06-12-2015,First Class,JE-15610,Jim Epp,Corporate,United States,Lakeland,...,33801.0,South,OFF-ST-10003816,Office Supplies,Storage,Fellowes High-Stak Drawer Files,563.808,4,0.2,21.1428
9995,1442,CA-2017-128160,12/19/2017,12/24/2017,Second Class,MM-17920,Michael Moore,Consumer,United States,San Francisco,...,94110.0,West,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,36.672,2,0.2,11.4600
9996,4511,CA-2016-119935,11-10-2016,11/14/2016,Standard Class,KM-16225,Kalyca Meade,Corporate,United States,Springfield,...,65807.0,Central,FUR-FU-10001085,Furniture,Furnishings,3M Polarizing Light Filter Sleeves,37.300,2,0.0,17.1580
9997,40,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041.0,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3,0.3,-15.1470
9998,4510,CA-2017-167003,5/23/2017,5/29/2017,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Los Angeles,...,90036.0,West,FUR-TA-10001520,Furniture,Tables,"Lesro Sheffield Collection Coffee Table, End T...",171.288,3,0.2,-6.4233

In [34]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,10044.000000,10004.000000,10004.000000,10044.000000,10044.000000,10004.000000
mean,4994.465253,55154.199320,255.108238,3.790422,0.156261,28.667871
std,2885.342882,32037.893863,1702.917481,2.224568,0.206516,233.940828
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2497.750000,23223.000000,17.332500,2.000000,0.000000,1.713750
50%,4989.500000,55901.000000,54.780000,3.000000,0.200000,8.636000
75%,7492.250000,90008.000000,209.970000,5.000000,0.200000,29.331600
max,9994.000000,99301.000000,121504.000000,14.000000,0.800000,8399.976000

In [35]:
print("Minimum Sales values: Rs.",df['Sales'].min())
print("Maximum Sales values: Rs.",df['Sales'].max())
print("Average Profit: Rs.",round(df['Profit'].mean(),2))
print("Maximum Discount: Rs.",df['Discount'].max())

Minimum Sales values: Rs. 0.444
Maximum Sales values: Rs. 121504.0
Average Profit: Rs. 28.67
Maximum Discount: Rs. 0.8

In [36]:
print(df['Category'].value_counts())
print("\nCategory with most records:",df['Category'].value_counts().idxmax())

Category
Office Supplies    5994
Furniture          2113
Technology         1837
office supplies      61
furniture            20
technology           19
Name: count, dtype: int64

Category with most records: Office Supplies

In [37]:
print(df['Region'].value_counts())
print("\nRegion with fewest records:",df['Region'].value_counts().idxmin())

Region
West       3219
East       2860
Central    2335
South      1630
Name: count, dtype: int64

Region with fewest records: South

In [38]:
print(df['Segment'].value_counts())
print("\nSegment appearing most frequently:",df['Segment'].value_counts().idxmax())

Segment
Consumer       5212
Corporate      3039
Home Office    1793
Name: count, dtype: int64

Segment appearing most frequently: Consumer

In [39]:
print("Before conversion:")
print("Data type of Order Date:",df['Order Date'].dtype)
print()
df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
print("After conversion:")
print("Data type of Order Date:",df['Order Date'].dtype)

Before conversion:
Data type of Order Date: str

After conversion:
Data type of Order Date: datetime64[us]

In [40]:
print("Before conversion:")
print("Data type of Ship Date:",df['Ship Date'].dtype)
print()
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")
print("After conversion:")
print("Data type of Ship Date:",df['Ship Date'].dtype)

Before conversion:
Data type of Ship Date: str

After conversion:
Data type of Ship Date: datetime64[us]

In [41]:
equal = '=' * 64
print(f"{equal} DATA QUALITY REPORT {equal}\n")
print("Total Missing values          :",  df.isnull().sum().sum())
print("\nTotal Duplicate Rows          :", df.duplicated().sum())
print("\nNumerical Column Observation  :")
display(df.describe())
print("\nCategorical Column Observation:\n",df['Category'].value_counts())
print("\nDate Column Observation (dtype):",df['Order Date'].dtype)
print("\nSummary after observation      : The dataset contains 10,044 records with retail sales information, including order details, products, sales, discounts, and profits. It has 160 missing values and 48 duplicate rows, indicating that data cleaning is required before analysis. Most transactions belong to the Office Supplies category, and there are inconsistent category names (e.g., Office Supplies and office supplies), which should be standardized. The Order Date and Ship Date columns have been successfully converted to datetime format, making the dataset ready for time-based analysis.")
print('=' * 150)

================================================================ DATA QUALITY REPORT ================================================================

Total Missing values          : 160

Total Duplicate Rows          : 48

Numerical Column Observation  :

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,10044.000000,10044,10044,10004.000000,10004.000000,10044.000000,10044.000000,10004.000000
mean,4994.465253,2016-04-30 22:05:35.483871,2016-05-04 21:06:14.193548,55154.199320,255.108238,3.790422,0.156261,28.667871
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2497.750000,2015-05-25 00:00:00,2015-05-28 00:00:00,23223.000000,17.332500,2.000000,0.000000,1.713750
50%,4989.500000,2016-06-26 00:00:00,2016-06-30 00:00:00,55901.000000,54.780000,3.000000,0.200000,8.636000
75%,7492.250000,2017-05-14 00:00:00,2017-05-18 06:00:00,90008.000000,209.970000,5.000000,0.200000,29.331600
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,121504.000000,14.000000,0.800000,8399.976000
std,2885.342882,NaN,NaN,32037.893863,1702.917481,2.224568,0.206516,233.940828

Categorical Column Observation:
 Category
Office Supplies    5994
Furniture          2113
Technology         1837
office supplies      61
furniture            20
technology           19
Name: count, dtype: int64

Date Column Observation (dtype): datetime64[us]

Summary after observation      : The dataset contains 10,044 records with retail sales information, including order details, products, sales, discounts, and profits. It has 160 missing values and 48 duplicate rows, indicating that data cleaning is required before analysis. Most transactions belong to the Office Supplies category, and there are inconsistent category names (e.g., Office Supplies and office supplies), which should be standardized. The Order Date and Ship Date columns have been successfully converted to datetime format, making the dataset ready for time-based analysis.
======================================================================================================================================================