In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Superstore_Messy.csv')

print("📊 STARTING THE CLEANING PIPELINE")
print("=" * 60)
print(f"   Rows:           {len(df)}")
print(f"   Missing values: {df.isnull().sum().sum()}")
print(f"   Duplicates:     {df.duplicated().sum()}")
print(f"   Date type:      {df['Order Date'].dtype}")
print("=" * 60)

📊 STARTING THE CLEANING PIPELINE
============================================================
   Rows:           10044
   Missing values: 160
   Duplicates:     48
   Date type:      str
============================================================

In [3]:
clean_df = df.copy()
clean_df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name    40
Segment           0
Country           0
City              0
State             0
Postal Code      40
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales            40
Quantity          0
Discount          0
Profit           40
dtype: int64

In [4]:
print("-------- Handling missing values in Customer Names --------")
print("Missing values in Customer Name BEFORE handling:", clean_df["Customer Name"].isnull().sum())
clean_df["Customer Name"] = clean_df["Customer Name"].fillna("Unknown")
print("Missing values in Customer Name AFTER handling:", clean_df["Customer Name"].isnull().sum())

print("\n-------- Handling missing values in Postal Code --------")
print("Missing values in Postal Code BEFORE handling:", clean_df["Postal Code"].isnull().sum())
clean_df = clean_df.dropna(subset = ["Postal Code"])
print("Missing values in Postal Code AFTER handling:", clean_df["Postal Code"].isnull().sum())

print("\n-------- Handling missing values in Sales and Profit --------")
print("Missing values in Sales BEFORE handling:", clean_df["Sales"].isnull().sum())
print("Missing values in Profit BEFORE handling:", clean_df["Profit"].isnull().sum())
for col in ["Sales", "Profit"]:
    clean_df[col] = clean_df[col].fillna(clean_df[col].median())
print("\nMissing values in Sales AFTER handling:", clean_df["Sales"].isnull().sum())
print("Missing values in Profit AFTER handling:", clean_df["Profit"].isnull().sum())

-------- Handling missing values in Customer Names --------
Missing values in Customer Name BEFORE handling: 40
Missing values in Customer Name AFTER handling: 0

-------- Handling missing values in Postal Code --------
Missing values in Postal Code BEFORE handling: 40
Missing values in Postal Code AFTER handling: 0

-------- Handling missing values in Sales and Profit --------
Missing values in Sales BEFORE handling: 40
Missing values in Profit BEFORE handling: 40

Missing values in Sales AFTER handling: 0
Missing values in Profit AFTER handling: 0

In [5]:
print("AFTER DEALING WITH MISSING VALUES:\n", clean_df.isnull().sum())

AFTER DEALING WITH MISSING VALUES:
 Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [6]:
print("Rows before dropping duplicates:", len(clean_df))
clean_df = clean_df.drop_duplicates()
print("Rows after deleting duplicates:", len(clean_df))

Rows before dropping duplicates: 10004
Rows after deleting duplicates: 9956

In [7]:
print("INITIAL DATA TYPE OF DATES IN DATASET")
print(clean_df[["Order Date", "Ship Date"]].dtypes)

print("\nCONVERTING TO DATETIME")
clean_df["Order Date"] = pd.to_datetime(clean_df["Order Date"], format = "mixed")
clean_df["Ship Date"] = pd.to_datetime(clean_df["Ship Date"], format = "mixed")
print("\nAFTER CONVERSION")
print(clean_df[["Order Date", "Ship Date"]].dtypes)

INITIAL DATA TYPE OF DATES IN DATASET
Order Date    str
Ship Date     str
dtype: object

CONVERTING TO DATETIME

AFTER CONVERSION
Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [8]:
columns = ['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name']

for col in columns:
    clean_df[col] = clean_df[col].str.strip().str.title()
    print(f"Text column '{col}' cleaned (strip + title case)")

Text column 'Order ID' cleaned (strip + title case)
Text column 'Ship Mode' cleaned (strip + title case)
Text column 'Customer ID' cleaned (strip + title case)
Text column 'Customer Name' cleaned (strip + title case)
Text column 'Segment' cleaned (strip + title case)
Text column 'Country' cleaned (strip + title case)
Text column 'City' cleaned (strip + title case)
Text column 'State' cleaned (strip + title case)
Text column 'Region' cleaned (strip + title case)
Text column 'Product ID' cleaned (strip + title case)
Text column 'Category' cleaned (strip + title case)
Text column 'Sub-Category' cleaned (strip + title case)
Text column 'Product Name' cleaned (strip + title case)

In [9]:
print("Cleaned Data Information:")
clean_df.info()
print()

print("Missing Values after cleaning")
print(clean_df.isnull().sum())
print()

print("Data type of dates in dataframe")
print(clean_df[['Order Date', 'Ship Date']].dtypes)
print()

clean_df = clean_df.drop_duplicates()
print("Duplicate Rows after cleaning")
print(clean_df.duplicated().sum())
print()

Cleaned Data Information:
<class 'pandas.DataFrame'>
Index: 9956 entries, 0 to 10042
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9956 non-null   int64
 1   Order ID       9956 non-null   str
 2   Order Date     9956 non-null   datetime64[us]
 3   Ship Date      9956 non-null   datetime64[us]
 4   Ship Mode      9956 non-null   str
 5   Customer ID    9956 non-null   str
 6   Customer Name  9956 non-null   str
 7   Segment        9956 non-null   str
 8   Country        9956 non-null   str
 9   City           9956 non-null   str
 10  State          9956 non-null   str
 11  Postal Code    9956 non-null   float64
 12  Region         9956 non-null   str
 13  Product ID     9956 non-null   str
 14  Category       9956 non-null   str
 15  Sub-Category   9956 non-null   str
 16  Product Name   9956 non-null   str
 17  Sales          9956 non-null   float64
 18  Quantity       9956 non-null   int64
 19  Discount       9956 non-null   float64
 20  Profit         9956 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(2), str(13)
memory usage: 3.2 MB

Missing Values after cleaning
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Data type of dates in dataframe
Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

Duplicate Rows after cleaning
0

In [10]:
equal = '=' * 64
print(f"{equal} DATA CLEANING REPORT {equal}\n")
print(f"Rows after cleaning                    : {len(clean_df)}")
print("\nMissing Value Treatment using fillna() and dropna()")
print(f"Missing Before                         : {df.isnull().sum().sum()}")
print(f"Missing After                          : {clean_df.isnull().sum().sum()}")
print("\nDuplicate Value Treatment using drop_duplicates()")
print(f"Duplicates Before                      : {df.duplicated().sum()}")
print(f"Duplicates After                       : {clean_df.duplicated().sum()}")
print("\nDate dtype Treatment using pd.to_datetime()")
print(f"Date type of 'Order Date' Before       : {df['Order Date'].dtypes}")
print(f"Date type of 'Order Date' After        : {clean_df['Order Date'].dtypes}")
print(f"Date type of 'Ship Date' Before        : {df['Ship Date'].dtypes}")
print(f"Date type of 'Ship Date' After         : {clean_df['Ship Date'].dtypes}")
print("\nText cleaning was done to remove extraspace and case sesitive nature was preserved using .str.strip().title()")
print(f'\n1. Missing values were handled\n2. Duplicates were removed\n3. Date was changed to datetime datatype\n4. Text cleaning was performed\n5. DATA READY FOR FEATURE ENGINEERING\n6. Data Lost: {(len(df) - len(clean_df))/len(df)*100}\n')
print('=' * 150)

================================================================ DATA CLEANING REPORT ================================================================

Rows after cleaning                    : 9954

Missing Value Treatment using fillna() and dropna()
Missing Before                         : 160
Missing After                          : 0

Duplicate Value Treatment using drop_duplicates()
Duplicates Before                      : 48
Duplicates After                       : 0

Date dtype Treatment using pd.to_datetime()
Date type of 'Order Date' Before       : str
Date type of 'Order Date' After        : datetime64[us]
Date type of 'Ship Date' Before        : str
Date type of 'Ship Date' After         : datetime64[us]

Text cleaning was done to remove extraspace and case sesitive nature was preserved using .str.strip().title()

1. Missing values were handled
2. Duplicates were removed
3. Date was changed to datetime datatype
4. Text cleaning was performed
5. DATA READY FOR FEATURE ENGINEERING
6. Data Lost: 0.8960573476702508

======================================================================================================================================================

# *Feature Engineering*

In [11]:
featured_data =  clean_df.copy()

In [12]:
featured_data.info()

<class 'pandas.DataFrame'>
Index: 9954 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9954 non-null   int64
 1   Order ID       9954 non-null   str
 2   Order Date     9954 non-null   datetime64[us]
 3   Ship Date      9954 non-null   datetime64[us]
 4   Ship Mode      9954 non-null   str
 5   Customer ID    9954 non-null   str
 6   Customer Name  9954 non-null   str
 7   Segment        9954 non-null   str
 8   Country        9954 non-null   str
 9   City           9954 non-null   str
 10  State          9954 non-null   str
 11  Postal Code    9954 non-null   float64
 12  Region         9954 non-null   str
 13  Product ID     9954 non-null   str
 14  Category       9954 non-null   str
 15  Sub-Category   9954 non-null   str
 16  Product Name   9954 non-null   str
 17  Sales          9954 non-null   float64
 18  Quantity       9954 non-null   int64
 19  Discount       9954 non-null   float64
 20  Profit         9954 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(2), str(13)
memory usage: 3.2 MB

In [13]:
featured_data['Order Year'] = featured_data['Order Date'].dt.year
display(featured_data.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,South,Fur-Bo-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,South,Fur-Ch-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,Off-La-10000240,Office Supplies,Labels,Self-Adhesive Address Labels For Typewriters B...,14.6200,2,0.00,6.8714,2016
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,Fur-Ta-10000577,Furniture,Tables,Bretford Cr4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,Off-St-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015

In [14]:
featured_data['Order Month Name'] = featured_data['Order Date'].dt.month_name()
featured_data['Order Month'] = featured_data['Order Date'].dt.month
display(featured_data.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month Name,Order Month
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,November,11
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,November,11
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels For Typewriters B...,14.6200,2,0.00,6.8714,2016,June,6
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford Cr4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,October,10
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,October,10

In [15]:
featured_data['Delivery Days'] = featured_data['Ship Date'] - featured_data['Order Date']
display(featured_data.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month Name,Order Month,Delivery Days
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,November,11,3 days
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,November,11,3 days
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels For Typewriters B...,14.6200,2,0.00,6.8714,2016,June,6,4 days
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford Cr4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,October,10,7 days
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,October,10,7 days

In [16]:
featured_data['Profit Margin (%)'] = (featured_data['Profit'] / featured_data['Sales']) * 100
display(featured_data.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month Name,Order Month,Delivery Days,Profit Margin (%)
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,November,11,3 days,16.00
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,November,11,3 days,30.00
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels For Typewriters B...,14.6200,2,0.00,6.8714,2016,June,6,4 days,47.00
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford Cr4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,October,10,7 days,-40.00
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,October,10,7 days,11.25

In [17]:
featured_data['Profit Status'] = np.where(featured_data['Profit']>0, "Profit", "Loss")
display(featured_data.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Order Year,Order Month Name,Order Month,Delivery Days,Profit Margin (%),Profit Status
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,November,11,3 days,16.00,Profit
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,November,11,3 days,30.00,Profit
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,June,6,4 days,47.00,Profit
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,October,10,7 days,-40.00,Loss
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,October,10,7 days,11.25,Profit

In [18]:
featured_data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Order Year',
       'Order Month Name', 'Order Month', 'Delivery Days', 'Profit Margin (%)',
       'Profit Status'],
      dtype='str')

In [19]:
original_cols = df.columns.to_list()
added_cols = featured_data.columns.to_list()
featured_cols = []
for cols in added_cols:
    if cols not in original_cols:
        featured_cols.append(cols)

In [20]:
equal = '=' * 60
print(f"{equal} FEATURE ENGINEERING REPORT {equal}\n")
print("New columns created:",featured_cols)
display(featured_data.head())
# 1. Which year has the most orders?
print("Year with highest orders:",featured_data['Order Year'].value_counts().idxmax())
# 2. Which month has the most orders?
print("Month with highest orders:",featured_data['Order Month Name'].value_counts().idxmax())
# 3. What is the average delivery time?
print("Average Delivery Time:", featured_data['Delivery Days'].mean())
# 4. Which orders are loss-making?
print("\nLoss making orders:\n", featured_data[featured_data['Profit Status'] == 'Loss'][['Order ID', 'Product ID', 'Profit', 'Profit Status']])
# 5. What is the average profit margin?
print(f"\nAverage Profit margin: {round(featured_data['Profit Margin (%)'].mean(),3)}%")
print('=' * 150)

============================================================ FEATURE ENGINEERING REPORT ============================================================

New columns created: ['Order Year', 'Order Month Name', 'Order Month', 'Delivery Days', 'Profit Margin (%)', 'Profit Status']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Order Year,Order Month Name,Order Month,Delivery Days,Profit Margin (%),Profit Status
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,November,11,3 days,16.00,Profit
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,November,11,3 days,30.00,Profit
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,June,6,4 days,47.00,Profit
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,October,10,7 days,-40.00,Loss
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,October,10,7 days,11.25,Profit

Year with highest orders: 2017
Month with highest orders: November
Average Delivery Time: 3 days 22:58:57.070524

Loss making orders:
             Order ID       Product ID     Profit Profit Status
3     Us-2015-108966  Fur-Ta-10000577  -383.0310          Loss
14    Us-2015-118983  Off-Ap-10002311  -123.8580          Loss
15    Us-2015-118983  Off-Bi-10000756    -3.8160          Loss
23    Us-2017-156909  Fur-Ch-10002774    -1.0196          Loss
27    Us-2015-150630  Fur-Bo-10004834 -1665.0522          Loss
...              ...              ...        ...           ...
9921  Ca-2014-111360  Off-Bi-10003350    -4.5936          Loss
9931  Ca-2015-104948  Fur-Bo-10004357   -40.1960          Loss
9937  Ca-2016-164889  Fur-Ta-10001676    -1.7772          Loss
9962  Ca-2015-168088  Fur-Bo-10004218   -67.6704          Loss
9977  Us-2016-103674  Off-Fa-10003467     0.0000          Loss

[1922 rows x 4 columns]

Average Profit margin: 12.122%
======================================================================================================================================================

In [22]:
featured_data.shape

(9954, 27)